export const userAccessRoles = [
  {
    category: 'admin',
    uid: 'A42739568414737450Z',
    id: 1,
    access: [
      { name: 'Manage Project', key: 'manage_project', checked: true },
      { name: 'View Project', key: 'view_project', checked: true },
      { name: 'Update Unit Status', checked: true, key: 'update_unit_status' },
      { key: 'view_leads', name: 'View Leads', checked: true },
      { checked: true, name: 'Update Leads', key: 'update_leads' },
      { checked: true, key: 'manage_leads', name: 'Manage Leads' },
      { checked: true, key: 'manage_users', name: 'Manage Users' },
      { checked: true, name: 'View Users', key: 'view_users' },
      { name: 'View CRM', key: 'view_crm', checked: true },
      { checked: true, name: 'Update CRM', key: 'update_crm' },
      { checked: true, name: 'Manage CRM', key: 'manage_crm' },
      { checked: true, name: 'View roles', key: 'view_roles' },
      { name: 'Update Roles', key: 'update_roles', checked: true },
    ],
    type: 'Admin',
    role: 'admin',
  },
  {
    category: 'CRM',
    id: 2,
    uid: 'A65873091712635464Z',
    type: 'CRM Manager',
    access: [
      { name: 'Manage Project', checked: false, key: 'manage_project' },
      { name: 'View Project', checked: false, key: 'view_project' },
      { name: 'Update Unit Status', key: 'update_unit_status', checked: false },
      { name: 'View Leads', key: 'view_leads', checked: false },
      { checked: false, key: 'update_leads', name: 'Update Leads' },
      { checked: false, name: 'Manage Leads', key: 'manage_leads' },
      { name: 'Manage Users', checked: false, key: 'manage_users' },
      { key: 'view_users', checked: false, name: 'View Users' },
      { checked: true, name: 'View CRM', key: 'view_crm' },
      { name: 'Update CRM', key: 'update_crm', checked: true },
      { checked: true, key: 'manage_crm', name: 'Manage CRM' },
      { name: 'View roles', checked: false, key: 'view_roles' },
      { name: 'Update Roles', checked: false, key: 'update_roles' },
    ],
    role: 'crm-manager',
  },
  {
    uid: 'A17467271233249648Z',
    access: [
      { key: 'manage_project', name: 'Manage Project', checked: false },
      { key: 'view_project', checked: false, name: 'View Project' },
      { name: 'Update Unit Status', checked: false, key: 'update_unit_status' },
      { name: 'View Leads', key: 'view_leads', checked: false },
      { key: 'update_leads', name: 'Update Leads', checked: false },
      { key: 'manage_leads', checked: false, name: 'Manage Leads' },
      { name: 'Manage Users', key: 'manage_users', checked: false },
      { name: 'View Users', key: 'view_users', checked: false },
      { key: 'view_crm', name: 'View CRM', checked: true },
      { key: 'update_crm', checked: true, name: 'Update CRM' },
      { key: 'manage_crm', checked: false, name: 'Manage CRM' },
      { name: 'View roles', checked: false, key: 'view_roles' },
      { checked: false, name: 'Update Roles', key: 'update_roles' },
    ],
    type: 'CRM Executive',
    category: 'CRM',
    id: 3,
    role: 'crm-executive',
  },
  {
    category: 'HR',
    type: 'HR Manager',
    uid: 'A53516328944166360Z',
    access: [
      { name: 'Manage Project', checked: false, key: 'manage_project' },
      { checked: false, key: 'view_project', name: 'View Project' },
      { key: 'update_unit_status', checked: false, name: 'Update Unit Status' },
      { checked: false, name: 'View Leads', key: 'view_leads' },
      { checked: false, name: 'Update Leads', key: 'update_leads' },
      { name: 'Manage Leads', key: 'manage_leads', checked: false },
      { name: 'Manage Users', key: 'manage_users', checked: true },
      { name: 'View Users', key: 'view_users', checked: true },
      { checked: false, key: 'view_crm', name: 'View CRM' },
      { name: 'Update CRM', checked: false, key: 'update_crm' },
      { checked: false, name: 'Manage CRM', key: 'manage_crm' },
      { key: 'view_roles', checked: true, name: 'View roles' },
      { key: 'update_roles', name: 'Update Roles', checked: true },
    ],
    id: 4,
    role: 'hr-manager',
  },
  {
    uid: 'A78859930315020600Z',
    id: 5,
    category: 'HR',
    type: 'HR Executive',
    access: [
      { checked: false, name: 'Manage Project', key: 'manage_project' },
      { key: 'view_project', name: 'View Project', checked: false },
      { checked: false, name: 'Update Unit Status', key: 'update_unit_status' },
      { key: 'view_leads', name: 'View Leads', checked: false },
      { checked: false, key: 'update_leads', name: 'Update Leads' },
      { name: 'Manage Leads', key: 'manage_leads', checked: false },
      { checked: true, key: 'manage_users', name: 'Manage Users' },
      { key: 'view_users', name: 'View Users', checked: true },
      { key: 'view_crm', checked: false, name: 'View CRM' },
      { name: 'Update CRM', checked: false, key: 'update_crm' },
      { name: 'Manage CRM', checked: false, key: 'manage_crm' },
      { name: 'View roles', key: 'view_roles', checked: false },
      { checked: false, name: 'Update Roles', key: 'update_roles' },
    ],
    role: 'hr-executive',
  },
  {
    access: [
      { name: 'Manage Project', key: 'manage_project', checked: false },
      { checked: false, name: 'View Project', key: 'view_project' },
      { checked: false, name: 'Update Unit Status', key: 'update_unit_status' },
      { name: 'View Leads', key: 'view_leads', checked: false },
      { checked: false, name: 'Update Leads', key: 'update_leads' },
      { name: 'Manage Leads', checked: false, key: 'manage_leads' },
      { checked: false, name: 'Manage Users', key: 'manage_users' },
      { key: 'view_users', name: 'View Users', checked: false },
      { checked: false, key: 'view_crm', name: 'View CRM' },
      { name: 'Update CRM', key: 'update_crm', checked: false },
      { name: 'Manage CRM', key: 'manage_crm', checked: false },
      { checked: false, name: 'View roles', key: 'view_roles' },
      { checked: false, key: 'update_roles', name: 'Update Roles' },
    ],
    id: 6,
    uid: 'A17646437035948526Z',
    type: 'Legal Manager',
    category: 'LEGAL',
    role: 'legal-manager',
  },
  {
    id: 7,
    uid: 'A60052484155844296Z',
    category: 'LEGAL',
    type: 'Legal Executive',
    access: [
      { key: 'manage_project', checked: false, name: 'Manage Project' },
      { name: 'View Project', checked: false, key: 'view_project' },
      { key: 'update_unit_status', name: 'Update Unit Status', checked: false },
      { name: 'View Leads', key: 'view_leads', checked: false },
      { checked: false, key: 'update_leads', name: 'Update Leads' },
      { key: 'manage_leads', name: 'Manage Leads', checked: false },
      { name: 'Manage Users', checked: false, key: 'manage_users' },
      { name: 'View Users', key: 'view_users', checked: false },
      { name: 'View CRM', checked: false, key: 'view_crm' },
      { checked: false, name: 'Update CRM', key: 'update_crm' },
      { name: 'Manage CRM', key: 'manage_crm', checked: false },
      { checked: false, name: 'View roles', key: 'view_roles' },
      { name: 'Update Roles', checked: false, key: 'update_roles' },
    ],
    role: 'legal-executive',
  },
  {
    category: 'SALES',
    id: 8,
    type: 'Sales Manager',
    uid: 'A56057873139336480Z',
    access: [
      { name: 'Manage Project', key: 'manage_project', checked: false },
      { checked: false, key: 'view_project', name: 'View Project' },
      { key: 'update_unit_status', checked: false, name: 'Update Unit Status' },
      { name: 'View Leads', key: 'view_leads', checked: true },
      { key: 'update_leads', name: 'Update Leads', checked: true },
      { name: 'Manage Leads', checked: true, key: 'manage_leads' },
      { checked: false, key: 'manage_users', name: 'Manage Users' },
      { checked: false, name: 'View Users', key: 'view_users' },
      { checked: false, key: 'view_crm', name: 'View CRM' },
      { checked: false, key: 'update_crm', name: 'Update CRM' },
      { key: 'manage_crm', checked: false, name: 'Manage CRM' },
      { key: 'view_roles', name: 'View roles', checked: false },
      { checked: false, key: 'update_roles', name: 'Update Roles' },
    ],
    role: 'sales-manager',
  },
  {
    access: [
      { name: 'Manage Project', key: 'manage_project', checked: false },
      { checked: false, key: 'view_project', name: 'View Project' },
      { name: 'Update Unit Status', checked: false, key: 'update_unit_status' },
      { checked: true, name: 'View Leads', key: 'view_leads' },
      { checked: false, key: 'update_leads', name: 'Update Leads' },
      { name: 'Manage Leads', checked: false, key: 'manage_leads' },
      { checked: false, key: 'manage_users', name: 'Manage Users' },
      { name: 'View Users', checked: false, key: 'view_users' },
      { key: 'view_crm', checked: false, name: 'View CRM' },
      { key: 'update_crm', checked: false, name: 'Update CRM' },
      { key: 'manage_crm', checked: false, name: 'Manage CRM' },
      { checked: false, name: 'View roles', key: 'view_roles' },
      { checked: false, name: 'Update Roles', key: 'update_roles' },
    ],
    uid: 'A52027268104112460Z',
    id: 9,
    category: 'SALES',
    type: 'Sales Executive',
    role: 'sales-executive',
  },
  {
    access: [
      { name: 'Manage Project', key: 'manage_project', checked: false },
      { checked: false, key: 'view_project', name: 'View Project' },
      { name: 'Update Unit Status', checked: false, key: 'update_unit_status' },
      { checked: true, name: 'View Leads', key: 'view_leads' },
      { checked: false, key: 'update_leads', name: 'Update Leads' },
      { name: 'Manage Leads', checked: false, key: 'manage_leads' },
      { checked: false, key: 'manage_users', name: 'Manage Users' },
      { name: 'View Users', checked: false, key: 'view_users' },
      { key: 'view_crm', checked: false, name: 'View CRM' },
      { key: 'update_crm', checked: false, name: 'Update CRM' },
      { key: 'manage_crm', checked: false, name: 'Manage CRM' },
      { checked: false, name: 'View roles', key: 'view_roles' },
      { checked: false, name: 'Update Roles', key: 'update_roles' },
    ],
    uid: 'A52027268104112560Z',
    id: 10,
    category: 'SALES',
    type: 'CP Agent',
    role: 'cp-agent',
  },
  {
    id: 13,
    uid: 'A60052484155844296Z',
    category: 'PROJECT',
    type: 'Project manager',
    access: [
      { key: 'manage_project', checked: false, name: 'Manage Project' },
      { name: 'View Project', checked: false, key: 'view_project' },
      { key: 'update_unit_status', name: 'Update Unit Status', checked: false },
      { name: 'View Leads', key: 'view_leads', checked: false },
      { checked: false, key: 'update_leads', name: 'Update Leads' },
      { key: 'manage_leads', name: 'Manage Leads', checked: false },
      { name: 'Manage Users', checked: false, key: 'manage_users' },
      { name: 'View Users', key: 'view_users', checked: false },
      { name: 'View CRM', checked: false, key: 'view_crm' },
      { checked: false, name: 'Update CRM', key: 'update_crm' },
      { name: 'Manage CRM', key: 'manage_crm', checked: false },
      { checked: false, name: 'View roles', key: 'view_roles' },
      { name: 'Update Roles', checked: false, key: 'update_roles' },
    ],
    role: 'project-manager',
  },
  {
    id: 14,
    uid: 'A60052484155844296Z',
    category: 'PROJECT',
    type: 'Project Executive',
    access: [
      { key: 'manage_project', checked: false, name: 'Manage Project' },
      { name: 'View Project', checked: false, key: 'view_project' },
      { key: 'update_unit_status', name: 'Update Unit Status', checked: false },
      { name: 'View Leads', key: 'view_leads', checked: false },
      { checked: false, key: 'update_leads', name: 'Update Leads' },
      { key: 'manage_leads', name: 'Manage Leads', checked: false },
      { name: 'Manage Users', checked: false, key: 'manage_users' },
      { name: 'View Users', key: 'view_users', checked: false },
      { name: 'View CRM', checked: false, key: 'view_crm' },
      { checked: false, name: 'Update CRM', key: 'update_crm' },
      { name: 'Manage CRM', key: 'manage_crm', checked: false },
      { checked: false, name: 'View roles', key: 'view_roles' },
      { name: 'Update Roles', checked: false, key: 'update_roles' },
    ],
    role: 'project-executive',
  },
]
